[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sunflower"
version = "0.1.0"
authors = [
    {name = "Pável Hernández Reza", email = "phr2807@gmail.com" }]
description = "Gestor de conexión a bases de datos altamente personalizable."
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "annotated-types==0.7.0",
    "bcrypt==4.3.0",
    "numpy==2.4.2",
    "pandas==2.3.3",
    "pydantic==2.12.5",
    "pydantic_core==2.41.5",
    "PyJWT==2.10.1",
    "python-dateutil==2.9.0.post0",
    "pytz==2025.2",
    "six==1.17.0",
    "SQLAlchemy==2.0.41",
    "typing-inspection==0.4.2",
    "typing_extensions==4.15.0",
    "tzdata==2025.3",
]

[tool.setuptools]
package-dir = { "" = "src" }
