class MODEL_ID:
    BASE_MODEL = 1
    BASE_MODEL_FIELD = 2
    BASE_MODEL_FIELD_SELECTION = 3
    BASE_USERS = 4
    BASE_MODEL_ACCESS = 5
    BASE_MODEL_ACCESS_GROUPS = 6
    BASE_USERS_ROLE = 7
    BASE_USERS_SESSION = 8

ROOT_ID = 1
