class CredentialsError(Exception):
    ...

class InitializationError(Exception):
    ...

class InvalidPasswordError(Exception):
    ...

class URLFormatError(Exception):
    ...

class ExpiredSessionToken(Exception):
    ...

class MalformedCriteriaError(Exception):
    ...

class IlegalComputedFieldRegistration(Exception):
    ...
