from ..._module_types import NewRecord
from ..._constants import (
    MODEL_ID,
    MODEL_NAME,
    FIELD_LABEL,
    FIELD_NAME,
)
from ..._core import ENV_VARIABLES

BASE_USERS_INITIAL_DATA: NewRecord.User = {
    'name': ENV_VARIABLES.INTERNAL_USER.NAME,
    'login': ENV_VARIABLES.INTERNAL_USER.LOGIN,
    'active': False,
}

ModelData = tuple[str, list[dict]]

INITIAL_DATA: list[ModelData] = [
    (
        MODEL_NAME.BASE_MODEL,
        [
            {
                'model': MODEL_NAME.BASE_MODEL,
                'name': 'base_model',
                'label': 'Modelos',
                'description': 'Este modelo define los modelos de la base de datos.',
                'state': 'base',
            },
            {
                'model': MODEL_NAME.BASE_MODEL_FIELD,
                'name': 'base_model_field',
                'label': 'Campos',
                'description': 'Este modelo define los campos de la base de datos.',
                'state': 'base',
            },
            {
                'model': MODEL_NAME.BASE_MODEL_FIELD_SELECTION,
                'name': 'base_model_field_selection',
                'label': 'Tipo de selección',
                'description': 'Este modelo define los valores de selección para usarse como tipo de dato en campos de modelos.',
                'state': 'base',
            },
            {
                'model': MODEL_NAME.BASE_USERS,
                'name': 'base_users',
                'label': 'Usuarios',
                'description': 'Este modelo define la estructura de usuarios en la base de datos',
                'state': 'base',
            },
        ],
    ),
    (
        MODEL_NAME.BASE_MODEL_FIELD,
        [
            {
                'name': FIELD_NAME.ID,
                'label': FIELD_LABEL.ID,
                'ttype': 'integer',
                'model_id': MODEL_ID.BASE_MODEL,
                'nullable': False,
                'readonly': True,
                'unique': True,
                'state': 'base',
            },
            {
                'name': FIELD_NAME.NAME,
                'label': FIELD_LABEL.NAME,
                'ttype': 'char',
                'model_id': MODEL_ID.BASE_MODEL,
                'is_required': True,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': FIELD_NAME.CREATE_DATE,
                'label': FIELD_LABEL.CREATE_DATE,
                'ttype': 'datetime',
                'model_id': MODEL_ID.BASE_MODEL,
                'nullable': False,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': FIELD_NAME.WRITE_DATE,
                'label': FIELD_LABEL.WRITE_DATE,
                'ttype': 'datetime',
                'model_id': MODEL_ID.BASE_MODEL,
                'nullable': False,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': 'model',
                'label': 'Modelo',
                'ttype': 'char',
                'model_id': MODEL_ID.BASE_MODEL,
                'nullable': False,
                'unique': True,
                'is_required': True,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': 'label',
                'label': 'Etiqueta',
                'ttype': 'char',
                'model_id': MODEL_ID.BASE_MODEL,
                'nullable': False,
                'is_required': True,
                'state': 'base',
            },
            {
                'name': 'description',
                'label': 'Descripción',
                'ttype': 'text',
                'model_id': MODEL_ID.BASE_MODEL,
                'state': 'base',
            },
            {
                'name': 'state',
                'label': 'Tipo de modelo',
                'ttype': 'selection',
                'model_id': MODEL_ID.BASE_MODEL,
                'nullable': False,
                'readonly': True,
                'default_value': 'generic',
                'state': 'base',
            },
            {
                'name': FIELD_NAME.ID,
                'label': FIELD_LABEL.ID,
                'ttype': 'integer',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'nullable': False,
                'readonly': True,
                'unique': True,
                'state': 'base',
            },
            {
                'name': FIELD_NAME.NAME,
                'label': FIELD_LABEL.NAME,
                'ttype': 'char',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'is_required': True,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': FIELD_NAME.CREATE_DATE,
                'label': FIELD_LABEL.CREATE_DATE,
                'ttype': 'datetime',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'nullable': False,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': FIELD_NAME.WRITE_DATE,
                'label': FIELD_LABEL.WRITE_DATE,
                'ttype': 'datetime',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'nullable': False,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': 'model_id',
                'label': 'Modelo',
                'ttype': 'many2one',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'nullable': False,
                'is_required': True,
                'readonly': True,
                'related_model_id': 1,
                'state': 'base',
            },
            {
                'name': 'label',
                'label': 'Etiqueta de campo',
                'ttype': 'char',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'nullable': False,
                'unique': True,
                'is_required': True,
                'state': 'base',
            },
            {
                'name': 'ttype',
                'label': 'Tipo',
                'ttype': 'selection',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'nullable': False,
                'is_required': True,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': 'nullable',
                'label': 'Nulo',
                'ttype': 'boolean',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'default_value': True,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': 'is_required',
                'label': 'Requerido',
                'ttype': 'boolean',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'default_value': False,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': 'readonly',
                'label': 'Solo lectura',
                'ttype': 'boolean',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'default_value': False,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': 'default_value',
                'label': 'Valor prestablecido',
                'ttype': 'char',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'nullable': True,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': 'unique',
                'label': 'Es valor único',
                'ttype': 'boolean',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'default_value': False,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': 'help_info',
                'label': 'Información de ayuda',
                'ttype': 'text',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'state': 'base',
            },
            {
                'name': 'related_model_id',
                'label': 'Modelo de relación',
                'ttype': 'many2one',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'readonly': True,
                'related_model_id': MODEL_ID.BASE_MODEL,
                'state': 'base',
            },
            {
                'name': 'related_field',
                'label': 'Campo relacionado',
                'ttype': 'char',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': 'state',
                'label': 'Tipo de campo',
                'ttype': 'selection',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'nullable': False,
                'default_value': 'generic',
                'readonly': True,
                'state': 'base',
            },
            {
                'name': FIELD_NAME.ID,
                'label': FIELD_LABEL.ID,
                'ttype': 'integer',
                'model_id': MODEL_ID.BASE_MODEL_FIELD_SELECTION,
                'nullable': False,
                'unique': True,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': FIELD_NAME.NAME,
                'label': FIELD_LABEL.NAME,
                'ttype': 'char',
                'model_id': MODEL_ID.BASE_MODEL_FIELD_SELECTION,
                'is_required': True,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': FIELD_NAME.CREATE_DATE,
                'label': FIELD_LABEL.CREATE_DATE,
                'ttype': 'datetime',
                'model_id': MODEL_ID.BASE_MODEL_FIELD_SELECTION,
                'nullable': False,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': FIELD_NAME.WRITE_DATE,
                'label': FIELD_LABEL.WRITE_DATE,
                'ttype': 'datetime',
                'model_id': MODEL_ID.BASE_MODEL_FIELD_SELECTION,
                'nullable': False,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': 'label',
                'label': 'Etiqueta',
                'ttype': 'char',
                'model_id': MODEL_ID.BASE_MODEL_FIELD_SELECTION,
                'is_required': True,
                'state': 'base',
            },
            {
                'name': 'field_id',
                'label': 'Campo',
                'ttype': 'many2one',
                'model_id': MODEL_ID.BASE_MODEL_FIELD_SELECTION,
                'related_model_id': MODEL_ID.BASE_MODEL_FIELD,
                'is_required': True,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': FIELD_NAME.ID,
                'label': FIELD_LABEL.ID,
                'ttype': 'integer',
                'model_id': MODEL_ID.BASE_USERS,
                'nullable': False,
                'unique': True,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': FIELD_NAME.NAME,
                'label': FIELD_LABEL.NAME,
                'ttype': 'char',
                'model_id': MODEL_ID.BASE_USERS,
                'is_required': True,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': FIELD_NAME.CREATE_DATE,
                'label': FIELD_LABEL.CREATE_DATE,
                'ttype': 'datetime',
                'model_id': MODEL_ID.BASE_USERS,
                'nullable': False,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': FIELD_NAME.WRITE_DATE,
                'label': FIELD_LABEL.WRITE_DATE,
                'ttype': 'datetime',
                'model_id': MODEL_ID.BASE_USERS,
                'nullable': False,
                'readonly': True,
                'state': 'base',
            },
            {
                'name': 'login',
                'label': 'Correo',
                'ttype': 'char',
                'model_id': MODEL_ID.BASE_USERS,
                'nullable': False,
                'unique': True,
                'is_required': True,
                'state': 'base',
            },
            {
                'name': 'password',
                'label': 'Contraseña',
                'ttype': 'char',
                'model_id': MODEL_ID.BASE_USERS,
                'nullable': False,
                # 'default_value': '[default_function]',
                'state': 'base',
            },
            {
                'name': FIELD_NAME.ACTIVE,
                'label': FIELD_LABEL.ACTIVE,
                'ttype': 'boolean',
                'model_id': MODEL_ID.BASE_USERS,
                'nullable': False,
                'default_value': True,
                'state': 'base',
            },
            {
                'name': 'sync',
                'label': 'Sincronizar',
                'ttype': 'boolean',
                'model_id': MODEL_ID.BASE_USERS,
                'nullable': False,
                'default_value': True,
                'state': 'base',
            },
        ],
    ),
    (
        MODEL_NAME.BASE_MODEL_FIELD,
        [
            {
                'name': 'field_ids',
                'label': 'Campos',
                'ttype': 'one2many',
                'model_id': MODEL_ID.BASE_MODEL,
                'readonly': True,
                'related_model_id': MODEL_ID.BASE_MODEL_FIELD,
                'related_field': 'model_id',
                'state': 'base',
            },
            {
                'name': 'related_field_ids',
                'label': 'Campos relacionados',
                'ttype': 'one2many',
                'model_id': MODEL_ID.BASE_MODEL,
                'readonly': True,
                'related_model_id': MODEL_ID.BASE_MODEL_FIELD,
                'related_field': 'related_model_id',
                'state': 'base',
            },
            {
                'name': 'selection_ids',
                'label': 'Valores de selección',
                'ttype': 'one2many',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'readonly': True,
                'state': 'base',
                'related_model_id': MODEL_ID.BASE_MODEL_FIELD_SELECTION,
                'related_field': 'field_id',
            },
        ]
    ),
    (
        MODEL_NAME.BASE_MODEL_FIELD_SELECTION,
        [
            {
                'name': 'base',
                'field_id': 16,
                'label': 'Campo base',
            },
            {
                'name': 'generic',
                'field_id': 16,
                'label': 'Campo genérico',
            },
            {
                'name': 'integer',
                'field_id': 23,
                'label': 'Entero',
            },
            {
                'name': 'char',
                'field_id': 23,
                'label': 'Caracter',
            },
            {
                'name': 'float',
                'field_id': 23,
                'label': 'Flotante',
            },
            {
                'name': 'boolean',
                'field_id': 23,
                'label': 'Booleano',
            },
            {
                'name': 'date',
                'field_id': 23,
                'label': 'Fecha',
            },
            {
                'name': 'datetime',
                'field_id': 23,
                'label': 'Fecha y hora',
            },
            {
                'name': 'time',
                'field_id': 23,
                'label': 'Tiempo',
            },
            {
                'name': 'duration',
                'field_id': 23,
                'label': 'Duración',
            },
            {
                'name': 'file',
                'field_id': 23,
                'label': 'Archivo',
            },
            {
                'name': 'text',
                'field_id': 23,
                'label': 'Texto largo',
            },
            {
                'name': 'selection',
                'field_id': 23,
                'label': 'Selección',
            },
            {
                'name': 'many2one',
                'field_id': 23,
                'label': 'Muchos a uno',
            },
            {
                'name': 'one2many',
                'field_id': 23,
                'label': 'Uno a muchos',
            },
            {
                'name': 'many2many',
                'field_id': 23,
                'label': 'Muchos a muchos',
            },
            {
                'name': 'base',
                'field_id': 32,
                'label': 'Campo base',
            },
            {
                'name': 'generic',
                'field_id': 32,
                'label': 'Campo genérico',
            },
        ],
    ),
    (
        MODEL_NAME.BASE_MODEL,
        [
            {
                'model': MODEL_NAME.BASE_MODEL_ACCESS,
                'name': 'base_model_access',
                'label': 'Permisos de acceso',
                'description': 'Este modelo define los permisos de acceso para cada modelo de la base de datos.',
            },
            {
                'model': MODEL_NAME.BASE_MODEL_ACCESS_GROUPS,
                'name': 'base_model_access_groups',
                'label': 'Grupos de acceso',
                'description': 'Este modelo define los grupos de acceso en la base de datos.'
            },
            {
                'model': MODEL_NAME.BASE_USERS_ROLE,
                'name': 'base_users_role',
                'label': 'Roles de usuario',
                'description': 'Este modelo define los roles de usuario en la base de datos',
            },
            {
                'model': MODEL_NAME.BASE_USERS_SESSION,
                'name': 'base_users_session',
                'label': 'Sesión de usuario',
                'description': 'Este modelo almacena las sesiones de los usuarios autenticados desde el frontend.'
            },
        ],
    ),
    (
        MODEL_NAME.BASE_MODEL_FIELD,
        [
            {
                'name': 'model_id',
                'model_id': MODEL_ID.BASE_MODEL_ACCESS,
                'label': 'Modelo',
                'ttype': 'many2one',
                'nullable': False,
                'is_required': True,
                'readonly': True,
                'related_model_id': MODEL_ID.BASE_MODEL,
            },
            {
                'name': 'label',
                'model_id': MODEL_ID.BASE_MODEL_ACCESS,
                'label': 'Etiqueta',
                'ttype': 'char',
            },
            {
                'name': 'perm_create',
                'model_id': MODEL_ID.BASE_MODEL_ACCESS,
                'label': 'Permiso para crear',
                'ttype': 'boolean',
                'default_value': False,
            },
            {
                'name': 'perm_read',
                'model_id': MODEL_ID.BASE_MODEL_ACCESS,
                'label': 'Permiso para leer',
                'ttype': 'boolean',
                'default_value': False,
            },
            {
                'name': 'perm_update',
                'model_id': MODEL_ID.BASE_MODEL_ACCESS,
                'label': 'Permiso para modificar',
                'ttype': 'boolean',
                'default_value': False,
            },
            {
                'name': 'perm_delete',
                'model_id': MODEL_ID.BASE_MODEL_ACCESS,
                'label': 'Permiso para eliminar',
                'ttype': 'boolean',
                'default_value': False,
            },
            {
                'name': 'label',
                'model_id': MODEL_ID.BASE_MODEL_ACCESS_GROUPS,
                'label': 'Etiqueta',
                'ttype': 'char',
                'is_required': True,
            },
            {
                'name': 'permission_ids',
                'model_id': MODEL_ID.BASE_MODEL_ACCESS_GROUPS,
                'label': 'Permisos',
                'ttype': 'many2many',
                'related_model_id': MODEL_ID.BASE_MODEL_ACCESS,
            },
            {
                'name': 'group_ids',
                'model_id': MODEL_ID.BASE_USERS_ROLE,
                'label': 'Grupos',
                'ttype': 'many2many',
                'nullable': False,
                'related_model_id': MODEL_ID.BASE_MODEL_ACCESS_GROUPS,
            },
            {
                'name': 'role_ids',
                'model_id': MODEL_ID.BASE_USERS,
                'label': 'Roles',
                'ttype': 'many2many',
                'related_model_id': MODEL_ID.BASE_USERS_ROLE,
            },
            {
                'name': 'user_id',
                'model_id': MODEL_ID.BASE_USERS_SESSION,
                'label': 'Usuario',
                'ttype': 'many2one',
                'nullable': False,
                'readonly': True,
                'is_required': True,
                'related_model_id': MODEL_ID.BASE_USERS,
            },
            {
                'name': 'expiration_date',
                'model_id': MODEL_ID.BASE_USERS_SESSION,
                'label': 'Fecha de expiración',
                'ttype': 'datetime',
                'nullable': False,
                'is_required': True,
                'readonly': True,
            },
        ]
    ),
    (
        MODEL_NAME.BASE_MODEL_ACCESS,
        [
            {
                'name': 'models_user',
                'model_id': MODEL_ID.BASE_MODEL,
                'label': 'Modelos / Usuario',
                'perm_read': True
            },
            {
                'name': 'models_admin',
                'model_id': MODEL_ID.BASE_MODEL,
                'label': 'Modelos / Administrador',
                'perm_create': True,
                'perm_read': True,
                'perm_update': True,
                'perm_delete': True,
            },
            {
                'name': 'model_fields_user',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'label': 'Campos de modelo / Usuario',
                'perm_read': True,
            },
            {
                'name': 'model_fields_admin',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'label': 'Campos de modelo / Administrador',
                'perm_create': True,
                'perm_read': True,
                'perm_update': True,
                'perm_delete': True,
            },
            {
                'name': 'model_field_selections_user',
                'model_id': MODEL_ID.BASE_MODEL_FIELD_SELECTION,
                'label': 'Valores de selección de campo / Usuario',
                'perm_read': True,
            },
            {
                'name': 'model_field_selections_admin',
                'model_id': MODEL_ID.BASE_MODEL_FIELD_SELECTION,
                'label': 'Valores de selección de campo / Administrador',
                'perm_create': True,
                'perm_read': True,
                'perm_update': True,
                'perm_delete': True,
            },
            {
                'name': 'users_user',
                'model_id': MODEL_ID.BASE_USERS,
                'label': 'Usuarios / Usuario',
                'perm_read': True,
            },
            {
                'name': 'users_admin',
                'model_id': MODEL_ID.BASE_USERS,
                'label': 'Usuarios / Administrador',
                'perm_create': True,
                'perm_read': True,
                'perm_update': True,
                'perm_delete': True,
            },
            {
                'name': 'model_access_user',
                'model_id': MODEL_ID.BASE_MODEL_ACCESS,
                'label': 'Permisos de acceso / Usuario',
                'perm_read': True,
            },
            {
                'name': 'model_access_admin',
                'model_id': MODEL_ID.BASE_MODEL_ACCESS,
                'label': 'Permisos de acceso / Administrador',
                'perm_create': True,
                'perm_read': True,
                'perm_update': True,
                'perm_delete': True,
            },
            {
                'name': 'base_model_group_user',
                'model_id': MODEL_ID.BASE_MODEL_ACCESS_GROUPS,
                'label': 'Grupos de acceso / Usuario',
                'perm_read': True,
            },
            {
                'name': 'base_model_group_admin',
                'model_id': MODEL_ID.BASE_MODEL_ACCESS_GROUPS,
                'label': 'Grupos de acceso / Administrador',
                'perm_create': True,
                'perm_read': True,
                'perm_update': True,
                'perm_delete': True,
            },
            {
                'name': 'base_users_role_user',
                'model_id': MODEL_ID.BASE_USERS_ROLE,
                'label': 'Roles de usuario / Usuario',
                'perm_read': True,
            },
            {
                'name': 'base_users_role_admin',
                'model_id': MODEL_ID.BASE_USERS_ROLE,
                'label': 'Roles de usuario / Administrador',
                'perm_create': True,
                'perm_read': True,
                'perm_update': True,
                'perm_delete': True,
            },
            {
                'name': 'base_users_session_user',
                'model_id': MODEL_ID.BASE_USERS_SESSION,
                'label': 'Sesiones de usuario / Usuario',
                'perm_read': True,
            },
            {
                'name': 'base_users_session_admin',
                'model_id': MODEL_ID.BASE_USERS_SESSION,
                'label': 'Sesiones de usuario / Administrador',
                'perm_create': True,
                'perm_read': True,
                'perm_update': True,
                'perm_delete': True,
            },
        ],
    ),
    (
        MODEL_NAME.BASE_MODEL_ACCESS_GROUPS,
        [
            {
                'name': 'base_user',
                'label': 'Usuario base',
                'permission_ids': [
                    (
                        'add',
                        [1, 3, 5, 7, 9, 11, 13, 15]
                    ),
                ],
            },
            {
                'name': 'admin_user',
                'label': 'Administrador',
                'permission_ids': [
                    (
                        'add',
                        [2, 4, 6, 8, 10, 12, 14, 16]
                    ),
                ],
            },
        ]
    ),
    (
        MODEL_NAME.BASE_USERS_ROLE,
        [
            {
                'name': 'Administrador de la base de datos',
                'group_ids': [
                    (
                        'add',
                        [1, 2]
                    ),
                ],
            }
        ]
    ),
    (
        MODEL_NAME.BASE_MODEL_FIELD,
        [
            {
                'name': 'profile_picture',
                'label': 'Foto de perfil',
                'ttype': 'file',
                'model_id': MODEL_ID.BASE_USERS,
                'state': 'base',
            },
            {
                'name': 'is_computed',
                'label': 'Computado',
                'ttype': 'boolean',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'readonly': True,
                'state': 'base',
                'nullable': False,
                'default_value': False,
            },
            {
                'name': FIELD_NAME.DISPLAY_NAME,
                'label': FIELD_LABEL.DISPLAY_NAME,
                'ttype': 'char',
                'model_id': MODEL_ID.BASE_MODEL,
                'state': 'base',
                'is_computed': True,
            },
            {
                'name': FIELD_NAME.DISPLAY_NAME,
                'label': FIELD_LABEL.DISPLAY_NAME,
                'ttype': 'char',
                'model_id': MODEL_ID.BASE_MODEL_FIELD,
                'state': 'base',
                'is_computed': True,
            },
            {
                'name': FIELD_NAME.DISPLAY_NAME,
                'label': FIELD_LABEL.DISPLAY_NAME,
                'ttype': 'char',
                'model_id': MODEL_ID.BASE_MODEL_FIELD_SELECTION,
                'state': 'base',
                'is_computed': True,
            },
            {
                'name': FIELD_NAME.DISPLAY_NAME,
                'label': FIELD_LABEL.DISPLAY_NAME,
                'ttype': 'char',
                'model_id': MODEL_ID.BASE_USERS,
                'state': 'base',
                'is_computed': True,
            },
            {
                'name': FIELD_NAME.DISPLAY_NAME,
                'label': FIELD_LABEL.DISPLAY_NAME,
                'ttype': 'char',
                'model_id': MODEL_ID.BASE_MODEL_ACCESS,
                'state': 'base',
                'is_computed': True,
            },
            {
                'name': FIELD_NAME.DISPLAY_NAME,
                'label': FIELD_LABEL.DISPLAY_NAME,
                'ttype': 'char',
                'model_id': MODEL_ID.BASE_MODEL_ACCESS_GROUPS,
                'state': 'base',
                'is_computed': True,
            },
            {
                'name': FIELD_NAME.DISPLAY_NAME,
                'label': FIELD_LABEL.DISPLAY_NAME,
                'ttype': 'char',
                'model_id': MODEL_ID.BASE_USERS_ROLE,
                'state': 'base',
                'is_computed': True,
            },
            {
                'name': FIELD_NAME.DISPLAY_NAME,
                'label': FIELD_LABEL.DISPLAY_NAME,
                'ttype': 'char',
                'model_id': MODEL_ID.BASE_USERS_SESSION,
                'state': 'base',
                'is_computed': True,
            },
        ]
    ),
]
