from ..._module_types import FieldProperties
from ..._constants import MODEL_NAME

FIELDS_ATTS: dict[str, dict[str, FieldProperties]] = {
    MODEL_NAME.BASE_MODEL: {
        'id': {
            'ttype': 'integer',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'name': {
            'ttype': 'char',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'create_date': {
            'ttype': 'datetime',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'write_date': {
            'ttype': 'datetime',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'display_name': {
            'ttype': 'char',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': True,
        },
        'model': {
            'ttype': 'char',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'label': {
            'ttype': 'char',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'description': {
            'ttype': 'text',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'state': {
            'ttype': 'selection',
            'related_model': None,
            'related_field': None,
            'selection_values': [
                'base',
                'generic',
            ],
            'is_computed': False,
        },
        'field_ids': {
            'ttype': 'one2many',
            'related_model': MODEL_NAME.BASE_MODEL_FIELD,
            'related_field': 'model_id',
            'selection_values': [],
            'is_computed': False,
        },
        'related_field_ids': {
            'ttype': 'one2many',
            'related_model': MODEL_NAME.BASE_MODEL_FIELD,
            'related_field': 'related_model_id',
            'selection_values': [],
            'is_computed': False,
        },
    },
    MODEL_NAME.BASE_MODEL_FIELD: {
        'id': {
            'ttype': 'integer',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'name': {
            'ttype': 'char',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'create_date': {
            'ttype': 'datetime',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'write_date': {
            'ttype': 'datetime',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'display_name': {
            'ttype': 'char',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': True,
        },
        'model_id': {
            'ttype': 'many2one',
            'related_model': MODEL_NAME.BASE_MODEL,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'label': {
            'ttype': 'char',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'ttype': {
            'ttype': 'selection',
            'related_model': None,
            'related_field': None,
            'selection_values': [
                'integer',
                'char',
                'float',
                'boolean',
                'date',
                'datetime',
                'time',
                'duration',
                'file',
                'text',
                'selection',
                'many2one',
                'one2many',
                'many2many',
            ],
            'is_computed': False,
        },
        'nullable': {
            'ttype': 'boolean',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'is_required': {
            'ttype': 'boolean',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'readonly': {
            'ttype': 'boolean',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'default_value': {
            'ttype': 'char',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'unique': {
            'ttype': 'boolean',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'help_info': {
            'ttype': 'text',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'related_model_id': {
            'ttype': 'many2one',
            'related_model': MODEL_NAME.BASE_MODEL,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'related_field': {
            'ttype': 'char',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
        'state': {
            'ttype': 'selection',
            'related_model': None,
            'related_field': None,
            'selection_values': [
                'base',
                'generic',
            ],
            'is_computed': False,
        },
        'selection_ids': {
            'ttype': 'one2many',
            'related_model': MODEL_NAME.BASE_MODEL_FIELD_SELECTION,
            'related_field': 'field_id',
            'selection_values': [],
            'is_computed': False,
        },
        'is_computed': {
            'ttype': 'boolean',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': False,
        },
    },
    MODEL_NAME.BASE_MODEL_FIELD_SELECTION: {
        'id': {
            'ttype': 'integer',
            'related_model': None,
            'related_field': None,
            'is_computed': False,
        },
        'name': {
            'ttype': 'char',
            'related_model': None,
            'related_field': None,
            'is_computed': False,
        },
        'create_date': {
            'ttype': 'datetime',
            'related_model': None,
            'related_field': None,
            'is_computed': False,
        },
        'write_date': {
            'ttype': 'datetime',
            'related_model': None,
            'related_field': None,
            'is_computed': False,
        },
        'display_name': {
            'ttype': 'char',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': True,
        },
        'label': {
            'ttype': 'char',
            'related_model': None,
            'related_field': None,
            'is_computed': False,
        },
        'field_id': {
            'ttype': 'many2one',
            'related_model': MODEL_NAME.BASE_MODEL_FIELD,
            'related_field': None,
            'is_computed': False,
        },
    },
    MODEL_NAME.BASE_USERS: {
        'id': {
            'ttype': 'integer',
            'related_model': None,
            'related_field': None,
            'is_computed': False,
        },
        'name': {
            'ttype': 'char',
            'related_model': None,
            'related_field': None,
            'is_computed': False,
        },
        'create_date': {
            'ttype': 'datetime',
            'related_model': None,
            'related_field': None,
            'is_computed': False,
        },
        'write_date': {
            'ttype': 'datetime',
            'related_model': None,
            'related_field': None,
            'is_computed': False,
        },
        'display_name': {
            'ttype': 'char',
            'related_model': None,
            'related_field': None,
            'selection_values': [],
            'is_computed': True,
        },
        'login': {
            'ttype': 'char',
            'related_model': None,
            'related_field': None,
            'is_computed': False,
        },
        'password': {
            'ttype': 'char',
            'related_model': None,
            'related_field': None,
            'is_computed': False,
        },
        'active': {
            'ttype': 'boolean',
            'related_model': None,
            'related_field': None,
            'is_computed': False,
        },
        'sync': {
            'ttype': 'boolean',
            'related_model': None,
            'related_field': None,
            'is_computed': False,
        },
        'profile_picture': {
            'ttype': 'file',
            'related_model': None,
            'related_field': None,
            'is_computed': False,
        },
    },
}